require "option"
require "keymaps"
require "plugins"
require "colorscheme"
require "telescops"
require "treesitter"
require "undotree"
require "autopairs"
require "lsp"
require "lsp.cmp"
require "project"
require "tools.git.gitsigns"
require "tools.git.diffview"
require "tools.comment"
require "autocommand"

